services:
  - type: web
    name: candle-store
    runtime: ruby
    plan: starter  # or standard/pro based on your needs
    env: ruby
    region: oregon
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: candle-store-db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false  # You'll set this manually in Render dashboard
      - key: RAILS_ENV
        value: production
      - key: RAILS_SERVE_STATIC_FILES
        value: true
      - key: RAILS_LOG_TO_STDOUT
        value: true
    # Persistent disk for image storage
    disk:
      name: candle-store-disk
      mountPath: /opt/render/project/storage
      sizeGB: 1  # Start with 1GB, increase as needed

databases:
  - name: candle-store-db
    databaseName: candle_store_production
    user: candle_store_user
    plan: starter  # Free tier